version: '3'

services:
  coordinator:
    build: presto-coordinator/.
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: coordinator
  worker0:
    build: presto-worker/.
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: worker0
  worker1:
    image: docker-presto-cluster_worker0:latest
    container_name: "worker1"
    ports:
      - "8082:8081"
    command: worker1
